In [1]:
print("Hello UPES !")

Hello UPES !


In [5]:
x=10
y=3.5
course="Data Visualization"

print(x,y,course)

10 3.5 Data Visualization


In [8]:
#Control flow

x=-5
if x>0:
  print("Positive")
elif x==0:
  print("Zero")
else:
  print("Negative")

Negative


In [9]:
#Looping statements
#for loop
for i in range(1,6):
  print(i)

1
2
3
4
5


In [10]:
#for loop
fruits=["apple","banana","mango"]
for f in fruits:
  print("I Like", f)

I Like apple
I Like banana
I Like mango


In [11]:
#while loop
count=1
while count<=5:
  print("count is", count)
  count=count+1

count is 1
count is 2
count is 3
count is 4
count is 5


In [13]:
#break
for i in range(1,10):
  if i==5:
    break
  print(i)

1
2
3
4


In [14]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [15]:
#continue

for i in range(1,10):
  if i==5:
    continue
  print(i)

1
2
3
4
6
7
8
9


In [16]:
#use a user defined function

def add(a,b):
  return a+b



In [17]:
print(add(5,3))

8


In [19]:
#Numpy Library
import numpy as np



In [20]:
# create an array

arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [21]:
max_value=np.max(arr)
min_value=np.min(arr)

print("maximum:",max_value)
print("Minimum:",min_value)

maximum: 6
Minimum: 1


In [23]:
#Create a matrix

matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
sum =matrix1+matrix2
print(matrix1)
print(matrix2)
print(sum)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [24]:
#Random Matrix Creation

random_matrix=np.random.rand(5,6)
print(random_matrix)

[[0.56417585 0.33576018 0.33797671 0.46443397 0.7002613  0.91539221]
 [0.05179868 0.02168184 0.88898842 0.11624544 0.14499469 0.92195913]
 [0.4496759  0.97540598 0.00572701 0.63149571 0.4742824  0.40077015]
 [0.25070266 0.27955741 0.49902541 0.73548525 0.77076611 0.37640887]
 [0.72167599 0.08116782 0.34005528 0.81672229 0.41116959 0.10386986]]


In [27]:
#Random Matrix creation with integer values
random_integer=np.random.randint(0,100,size=(5,6))
print(random_integer)

[[37  5 73 15 72 37]
 [83 76 55 66 87 44]
 [76 65 49 34 79 10]
 [93 22 43  9 58 69]
 [89 71  3 92 54 76]]


In [30]:
#Adding a new row
new_row=np.random.rand(1,6)
print(new_row)

[[0.90498401 0.33636969 0.96522499 0.23799433 0.13153695 0.57421338]]


In [31]:
random_matrix=np.vstack((random_matrix,new_row))
print(random_matrix)

[[0.56417585 0.33576018 0.33797671 0.46443397 0.7002613  0.91539221]
 [0.05179868 0.02168184 0.88898842 0.11624544 0.14499469 0.92195913]
 [0.4496759  0.97540598 0.00572701 0.63149571 0.4742824  0.40077015]
 [0.25070266 0.27955741 0.49902541 0.73548525 0.77076611 0.37640887]
 [0.72167599 0.08116782 0.34005528 0.81672229 0.41116959 0.10386986]
 [0.90498401 0.33636969 0.96522499 0.23799433 0.13153695 0.57421338]]


In [36]:
#Slicing

resultant_matrix=random_matrix[:,0:4]
print(resultant_matrix)

[[0.56417585 0.33576018 0.33797671 0.46443397]
 [0.05179868 0.02168184 0.88898842 0.11624544]
 [0.4496759  0.97540598 0.00572701 0.63149571]
 [0.25070266 0.27955741 0.49902541 0.73548525]
 [0.72167599 0.08116782 0.34005528 0.81672229]
 [0.90498401 0.33636969 0.96522499 0.23799433]]


In [37]:
#Pandas Library

import pandas as pd

In [38]:
df=pd.read_csv("/content/Salary_Data.csv")

In [39]:
print(df)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0
